service: challenge
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    ACCOUNTS_TABLE: accounts-dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"

resources:
  Resources:
    AccountsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "Email"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "Email"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: ${self:provider.environment.ACCOUNTS_TABLE}

functions:
  accountcreation:
    handler: src/api/accounts/createAccount.createAccount
    memorySize: 128
    description: Create a new account
    events:
      - http: 
          path: accounts
          method: post
